<a href="https://colab.research.google.com/github/TanyaYadav/Deep-Learning-Projects/blob/main/Movie_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Movie Recommender System***

###**Unzipping file for fetching dataset**

In [ ]:
!unzip /content/tmdb_5000_credits.csv.zip

Archive:  /content/tmdb_5000_credits.csv.zip
replace tmdb_5000_credits.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: tmdb_5000_credits.csv

In [ ]:
!unzip /content/tmdb_5000_movies.csv.zip

Archive:  /content/tmdb_5000_movies.csv.zip
replace tmdb_5000_movies.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: tmdb_5000_movies.csv

###***Importing libraries***

In [ ]:
import numpy as np
import pandas as pd
import nltk
import ast

###***Getting data***

In [ ]:
movies= pd.read_csv('/content/tmdb_5000_movies.csv')
credits= pd.read_csv('/content/tmdb_5000_credits.csv')

In [ ]:
movies.head(2)

      budget  ... vote_count
0  237000000  ...      11800
1  300000000  ...       4500

[2 rows x 20 columns]

In [ ]:
movies.shape

(4803, 20)

In [ ]:
credits.head(2)

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...

[2 rows x 4 columns]

In [ ]:
credits.shape

(4803, 4)

###***Merging both datasets on 'title' column***

In [ ]:
movies= movies.merge(credits,on='title')

In [ ]:
movies

         budget  ...                                               crew
0     237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1     300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...         ...  ...                                                ...
4804     220000  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805       9000  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806          0  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807          0  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808          0  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4809 rows x 23 columns]

###***Getting necessary columns from the dataset***

In [ ]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [ ]:
movies.head(5)

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

###*The ast (Abstract Syntax Trees) module helps Python applications to process trees of the Python abstract syntax grammar.*

In [ ]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [ ]:
movies.dropna(inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [ ]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [ ]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [ ]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [ ]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])
movies

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

      movie_id  ...                                               crew
0        19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1          285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3        49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4        49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...        ...  ...                                                ...
4804      9367  ...  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805     72766  ...  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806    231617  ...  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807    126186  ...  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808     25975  ...  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4806 rows x 7 columns]

In [ ]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [ ]:
movies['crew'] = movies['crew'].apply(fetch_director)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
movies.sample(5)

      movie_id  ...                    crew
1904     18147  ...             [Paul Feig]
1436     10012  ...            [Wes Craven]
3304    256687  ...          [Keith Parmer]
2030       783  ...  [Richard Attenborough]
1486      9600  ...          [Raja Gosnell]

[5 rows x 7 columns]

In [ ]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [ ]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
movies.head()

   movie_id  ...                crew
0     19995  ...      [JamesCameron]
1       285  ...     [GoreVerbinski]
2    206647  ...         [SamMendes]
3     49026  ...  [ChristopherNolan]
4     49529  ...     [AndrewStanton]

[5 rows x 7 columns]

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [ ]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

   movie_id  ...                                               tags
0     19995  ...  In the 22nd century, a paraplegic Marine is di...
1       285  ...  Captain Barbossa, long believed to be dead, ha...
2    206647  ...  A cryptic message from Bond’s past sends him o...
3     49026  ...  Following the death of District Attorney Harve...
4     49529  ...  John Carter is a war-weary, former military ca...

[5 rows x 3 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vector = cv.fit_transform(new['tags']).toarray()

In [ ]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vector.shape

(4806, 5000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(vector)

In [ ]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])

[(0, 1.0),
 (539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943),
 (507, 0.24846467329894412),
 (1444, 0.24397501823713333),
 (1920, 0.243599382882345),
 (582, 0.24147264420814754),
 (3730, 0.23904572186687872),
 (74, 0.22677868380553634),
 (3608, 0.2238868314198225),
 (322, 0.22230800575069137),
 (83, 0.22190115272469205),
 (4192, 0.22131333406899523),
 (2333, 0.2173253797873328),
 (1204, 0.21653278478430665),
 (47, 0.2164218276749025),
 (61, 0.2162249910469341),
 (495, 0.2162249910469341),
 (2409, 0.2138089935299395),
 (1537, 0.2125118592516207),
 (942, 0.21251185925162067),
 (972, 0.21251185925162067),
 (466, 0.2114722130550724),
 (1329, 0.21147221305507238),
 (2204, 0.2059714602177749),
 (151, 0.20498001542269692),
 (1201, 0.20283702113484398),
 (973, 0.2),
 (4048, 0.1980534816610477),
 (3162, 0.19518001458970666),
 (4405, 0.19518001458970666),
 (1275, 0.19518001458970663),
 (2786, 0.19518001458970663),
 (2971, 0.19477964490741226),
 (3538, 0.19451950503185494),
 (461, 0.1938916835823703),
 (3327, 0.1938916835823703),
 (305, 0.19320245583349133),
 (36, 0.19194297398747862),
 (931, 0.1916629694999819),
 (150, 0.18869127060994534),
 (220, 0.18832944617230335),
 (27, 0.18752289237539818),
 (2999, 0.18752289237539815),
 (300, 0.18708286933869708),
 (1321, 0.18442777839082936),
 (184, 0.1825741858350554),
 (4, 0.18257418583505536),
 (1071, 0.18257418583505536),
 (301, 0.18182745801939793),
 (373, 0.18018749253911176),
 (67, 0.17928429140015903),
 (46, 0.1765469659009499),
 (7, 0.1763834207376394),
 (2731, 0.17622684421256032),
 (1831, 0.17445567519772937),
 (1344, 0.1739313106957345),
 (149, 0.173137462139922),
 (2496, 0.17251638983558856),
 (26, 0.17142857142857143),
 (208, 0.1690308509457033),
 (661, 0.1690308509457033),
 (4010, 0.1690308509457033),
 (108, 0.16903085094570328),
 (838, 0.16903085094570328),
 (1808, 0.16673100431301852),
 (94, 0.16574838603294897),
 (2515, 0.16574838603294897),
 (1396, 0.16408253082847338),
 (581, 0.16265001215808886),
 (1297, 0.16239958858823),
 (4336, 0.16239958858823),
 (168, 0.16035674514745463),
 (1383, 0.16035674514745463),
 (31, 0.15971914124998493),
 (91, 0.15971914124998493),
 (3628, 0.15694120514358612),
 (311, 0.1564921592871903),
 (1965, 0.1553638665664663),
 (502, 0.1546617786679401),
 (111, 0.15430334996209188),
 (577, 0.15430334996209188),
 (3354, 0.15430334996209188),
 (158, 0.15289415743128765),
 (1355, 0.15289415743128765),
 (1178, 0.15179418517972906),
 (2169, 0.15179418517972906),
 (172, 0.15118578920369088),
 (490, 0.15118578920369088),
 (17, 0.15026857675938213),
 (1938, 0.14953343588376802),
 (422, 0.14754222271266348),
 (505, 0.14754222271266348),
 (1488, 0.14754222271266348),
 (41, 0.14638501094227999),
 (84, 0.1456438162508838),
 (52, 0.1449427589131121),
 (557, 0.1449427589131121),
 (568, 0.1449427589131121),
 (2686, 0.1449427589131121),
 (56, 0.14414999403128942),
 (249, 0.14414999403128942),
 (2584, 0.14414999403128942),
 (3999, 0.14414999403128942),
 (332, 0.14285714285714285),
 (1220, 0.14285714285714285),
 (1322, 0.14201432049934523),
 (487, 0.14098147537004826),
 (1327, 0.14098147537004826),
 (187, 0.14085904245475275),
 (1945, 0.14085904245475275),
 (1673, 0.1406421692815486),
 (2133, 0.1406421692815486),
 (2480, 0.1406421692815486),
 (4348, 0.1406421692815486),
 (413, 0.1389425035941821),
 (1833, 0.13801311186847084),
 (2620, 0.13801311186847084),
 (2970, 0.13801311186847084),
 (4490, 0.13801311186847084),
 (2873, 0.13801311186847082),
 (1015, 0.13710212427677043),
 (3409, 0.13710212427677043),
 (3622, 0.13710212427677043),
 (342, 0.13662601021279464),
 (127, 0.13572417850765922),
 (595, 0.13533299049019168),
 (1299, 0.13533299049019168),
 (134, 0.13522468075656266),
 (368, 0.13522468075656266),
 (1158, 0.13522468075656266),
 (3675, 0.1336306209562122),
 (1002, 0.13316902848554255),
 (68, 0.13259870882635919),
 (1047, 0.13259870882635919),
 (1096, 0.13259870882635919),
 (1658, 0.13259870882635919),
 (2378, 0.13259870882635919),
 (3376, 0.13259870882635919),
 (740, 0.13199091933711365),
 (1715, 0.1309307341415954),
 (529, 0.13041013273932528),
 (778, 0.13041013273932528),
 (1617, 0.13041013273932528),
 (483, 0.1301200097264711),
 (1747, 0.1301200097264711),
 (420, 0.12888481555661674),
 (1037, 0.12888481555661674),
 (1741, 0.12880163722232754),
 (238, 0.12777531299998796),
 (939, 0.12777531299998796),
 (2713, 0.12741179785940637),
 (3309, 0.12741179785940637),
 (1575, 0.1267731382092775),
 (4203, 0.1267731382092775),
 (228, 0.12598815766974242),
 (432, 0.12598815766974242),
 (3407, 0.12598815766974242),
 (28, 0.12555296411486888),
 (275, 0.12555296411486888),
 (1274, 0.12555296411486888),
 (2075, 0.12555296411486888),
 (2868, 0.12555296411486888),
 (4673, 0.12555296411486888),
 (549, 0.1246111965698067),
 (95, 0.12461119656980668),
 (50, 0.12344267996967351),
 (72, 0.12344267996967351),
 (579, 0.12344267996967351),
 (1982, 0.12344267996967351),
 (454, 0.12327841818038447),
 (2547, 0.12327841818038447),
 (1512, 0.12327841818038446),
 (653, 0.12298800925361816),
 (808, 0.12298800925361816),
 (123, 0.12198750911856666),
 (692, 0.12073632210407378),
 (1277, 0.12073632210407378),
 (1479, 0.12073632210407378),
 (3147, 0.12036162814275589),
 (169, 0.11952286093343936),
 (624, 0.11952286093343936),
 (2259, 0.11952286093343936),
 (3630, 0.11952286093343936),
 (3721, 0.11952286093343936),
 (166, 0.11952286093343935),
 (232, 0.11952286093343935),
 (294, 0.11952286093343935),
 (687, 0.11952286093343935),
 (859, 0.11952286093343935),
 (1616, 0.11952286093343935),
 (1574, 0.1187013882373396),
 (5, 0.1183452670827877),
 (10, 0.11769797726729994),
 (513, 0.11769797726729994),
 (1031, 0.11769797726729994),
 (2583, 0.11769797726729994),
 (3008, 0.11769797726729994),
 (199, 0.11720180773462385),
 (81, 0.11710800875382396),
 (627, 0.11633501014942217),
 (1373, 0.11633501014942217),
 (1727, 0.11633501014942217),
 (2323, 0.11633501014942217),
 (4000, 0.11633501014942217),
 (4018, 0.11633501014942217),
 (87, 0.11595420713048966),
 (126, 0.11595420713048966),
 (508, 0.11595420713048966),
 (777, 0.11501092655705902),
 (14, 0.11428571428571427),
 (854, 0.11428571428571427),
 (900, 0.11428571428571427),
 (1195, 0.11428571428571427),
 (2013, 0.11428571428571427),
 (2450, 0.11428571428571427),
 (3498, 0.11428571428571427),
 (1524, 0.11338934190276817),
 (1721, 0.11338934190276817),
 (2634, 0.11338934190276817),
 (3663, 0.11338934190276817),
 (4135, 0.11338934190276817),
 (141, 0.11338934190276816),
 (1019, 0.1129384878631564),
 (1497, 0.1129384878631564),
 (2439, 0.1129384878631564),
 (131, 0.1126872339638022),
 (330, 0.1126872339638022),
 (1082, 0.1126872339638022),
 (1294, 0.1126872339638022),
 (3340, 0.1126872339638022),
 (3620, 0.1126872339638022),
 (4097, 0.1126872339638022),
 (18, 0.11194341570991125),
 (102, 0.11194341570991125),
 (2106, 0.11194341570991125),
 (2760, 0.11194341570991125),
 (174, 0.11115400287534567),
 (266, 0.11115400287534567),
 (2072, 0.11115400287534567),
 (2181, 0.11115400287534567),
 (239, 0.11097419040461878),
 (3781, 0.11065666703449763),
 (35, 0.11065666703449761),
 (325, 0.11065666703449761),
 (773, 0.11065666703449761),
 (1156, 0.11065666703449761),
 (2521, 0.11065666703449761),
 (3055, 0.11065666703449761),
 (3954, 0.11065666703449761),
 (403, 0.11002971203391539),
 (295, 0.10968169942141635),
 (312, 0.10968169942141635),
 (535, 0.10968169942141635),
 (988, 0.10968169942141635),
 (1273, 0.10968169942141635),
 (3102, 0.10968169942141635),
 (4079, 0.10968169942141635),
 (754, 0.10826639239215334),
 (4230, 0.10826639239215334),
 (139, 0.10821091383745127),
 (4545, 0.10821091383745125),
 (105, 0.10811249552346706),
 (233, 0.10811249552346706),
 (476, 0.10811249552346706),
 (2456, 0.10811249552346706),
 (2762, 0.10811249552346706),
 (3839, 0.10811249552346706),
 (4198, 0.10811249552346706),
 (4623, 0.10811249552346706),
 (182, 0.10690449676496976),
 (334, 0.10690449676496976),
 (643, 0.10690449676496976),
 (898, 0.10690449676496976),
 (1056, 0.10690449676496976),
 (1109, 0.10690449676496976),
 (3783, 0.10690449676496976),
 (85, 0.10631548679075009),
 (33, 0.1057361065275362),
 (148, 0.1057361065275362),
 (157, 0.1057361065275362),
 (263, 0.1057361065275362),
 (715, 0.1057361065275362),
 (935, 0.1057361065275362),
 (1280, 0.1057361065275362),
 (1301, 0.1057361065275362),
 (1501, 0.1057361065275362),
 (2562, 0.1057361065275362),
 (2660, 0.1057361065275362),
 (4331, 0.1057361065275362),
 (129, 0.10559273546969093),
 (510, 0.10559273546969093),
 (1086, 0.10559273546969093),
 (3443, 0.10559273546969093),
 (3464, 0.10559273546969093),
 (4045, 0.10559273546969093),
 (307, 0.10460520656316097),
 (1233, 0.10432810619146021),
 (400, 0.10350983390135313),
 (660, 0.10350983390135313),
 (781, 0.10350983390135313),
 (1942, 0.10350983390135313),
 (2661, 0.10350983390135313),
 (4256, 0.10350983390135313),
 (270, 0.1031078524452934),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (371, 0.1031078524452934),
 (870, 0.1031078524452934),
 (1202, 0.1031078524452934),
 (1439, 0.1031078524452934),
 (412, 0.1019294382875251),
 (473, 0.1019294382875251),
 (813, 0.1019294382875251),
 (933, 0.1019294382875251),
 (1276, 0.1019294382875251),
 (2003, 0.1019294382875251),
 (2284, 0.1019294382875251),
 (292, 0.10141851056742199),
 (389, 0.10141851056742199),
 (530, 0.10141851056742199),
 (564, 0.10141851056742199),
 (691, 0.10141851056742199),
 (920, 0.10141851056742199),
 (1077, 0.10141851056742199),
 (1408, 0.10141851056742199),
 (2651, 0.10141851056742199),
 (3093, 0.10141851056742199),
 (3736, 0.10141851056742199),
 (410, 0.10079052613579392),
 (1823, 0.10079052613579392),
 (243, 0.09968895725584535),
 (785, 0.09960238411119947),
 (1089, 0.09960238411119947),
 (791, 0.0994490316197694),
 (1474, 0.0994490316197694),
 (1589, 0.0994490316197694),
 (1686, 0.0994490316197694),
 (1756, 0.0994490316197694),
 (2396, 0.0994490316197694),
 (2652, 0.0994490316197694),
 (589, 0.09862273454430757),
 (618, 0.09862273454430757),
 (1357, 0.09862273454430757),
 (2596, 0.09862273454430757),
 (43, 0.09759000729485333),
 (1846, 0.09759000729485333),
 (2488, 0.09759000729485333),
 (2796, 0.09759000729485333),
 (3154, 0.09759000729485333),
 (23, 0.09759000729485331),
 (142, 0.09759000729485331),
 (236, 0.09759000729485331),
 (362, 0.09759000729485331),
 (2093, 0.09759000729485331),
 (160, 0.09694584179118515),
 (206, 0.09694584179118515),
 (596, 0.09658905768325902),
 (1418, 0.09658905768325902),
 (12, 0.09583148474999097),
 (122, 0.09583148474999097),
 (511, 0.09583148474999097),
 (794, 0.09583148474999097),
 (922, 0.09583148474999097),
 (1027, 0.09583148474999097),
 (1306, 0.09583148474999097),
 (2840, 0.09583148474999097),
 (1832, 0.09561828874675149),
 (1924, 0.09561828874675149),
 (479, 0.09508728264112047),
 (1278, 0.09467621366623016),
 (21, 0.09416472308615166),
 (164, 0.09416472308615166),
 (242, 0.09416472308615166),
 (306, 0.09416472308615166),
 (960, 0.09416472308615166),
 (1249, 0.09416472308615166),
 (1523, 0.09416472308615166),
 (2817, 0.09416472308615166),
 (4468, 0.09416472308615166),
 (799, 0.09390602830316849),
 (1496, 0.09376144618769908),
 (2274, 0.09376144618769908),
 (2388, 0.09376144618769908),
 (2856, 0.09376144618769908),
 (4353, 0.09376144618769908),
 (4502, 0.09376144618769908),
 (4516, 0.09376144618769908),
 (4654, 0.09376144618769908),
 (2448, 0.09333167411831966),
 (75, 0.09258200997725513),
 (227, 0.09258200997725513),
 (349, 0.09258200997725513),
 (356, 0.09258200997725513),
 (369, 0.09258200997725513),
 (775, 0.09258200997725513),
 (901, 0.09258200997725513),
 (980, 0.09258200997725513),
 (1004, 0.09258200997725513),
 (1378, 0.09258200997725513),
 (1700, 0.09258200997725513),
 (1790, 0.09258200997725513),
 (3449, 0.09258200997725513),
 (3537, 0.09258200997725513),
 (3816, 0.09258200997725513),
 (4626, 0.09258200997725513),
 (63, 0.09200874124564722),
 (107, 0.09200874124564722),
 (170, 0.09200874124564722),
 (812, 0.09200874124564722),
 (2005, 0.09200874124564722),
 (2968, 0.09200874124564722),
 (32, 0.09116846116771035),
 (45, 0.09116846116771035),
 (363, 0.09116846116771035),
 (467, 0.09116846116771035),
 (491, 0.09116846116771035),
 (2498, 0.09116846116771035),
 (88, 0.09107651110783743),
 (112, 0.09107651110783743),
 (121, 0.09107651110783743),
 (245, 0.09107651110783743),
 (315, 0.09107651110783743),
 (814, 0.09107651110783743),
 (894, 0.09107651110783743),
 (937, 0.09107651110783743),
 (2167, 0.09107651110783743),
 (3301, 0.09107651110783743),
 (222, 0.09035079029052512),
 (381, 0.09035079029052512),
 (2880, 0.09035079029052512),
 (4737, 0.09035079029052512),
 (2386, 0.09009374626955588),
 (1, 0.08964214570007951),
 (96, 0.08964214570007951),
 (241, 0.08964214570007951),
 (547, 0.08964214570007951),
 (1113, 0.08964214570007951),
 (1142, 0.08964214570007951),
 (1269, 0.08964214570007951),
 (2247, 0.08964214570007951),
 (2251, 0.08964214570007951),
 (2304, 0.08964214570007951),
 (2794, 0.08964214570007951),
 (3091, 0.08964214570007951),
 (4259, 0.08964214570007951),
 (4657, 0.08964214570007951),
 (654, 0.089554732567929),
 (1282, 0.089554732567929),
 (103, 0.08877935232369503),
 (230, 0.08877935232369503),
 (1878, 0.08877935232369503),
 (39, 0.08827348295047496),
 (86, 0.08827348295047496),
 (98, 0.08827348295047496),
 (101, 0.08827348295047496),
 (203, 0.08827348295047496),
 (786, 0.08827348295047496),
 (899, 0.08827348295047496),
 (1207, 0.08827348295047496),
 (1473, 0.08827348295047496),
 (3428, 0.08827348295047495),
 (501, 0.0880237696271323),
 (1828, 0.0880237696271323),
 (19, 0.08728715609439694),
 (193, 0.08728715609439694),
 (1139, 0.08728715609439694),
 (1405, 0.08728715609439694),
 (2099, 0.08728715609439694),
 (2250, 0.08728715609439694),
 (2339, 0.08728715609439694),
 (3069, 0.08728715609439694),
 (3218, 0.08728715609439694),
 (3441, 0.08728715609439694),
 (4165, 0.08728715609439694),
 (4492, 0.08728715609439694),
 (4718, 0.08728715609439694),
 (257, 0.08696565534786725),
 (457, 0.08696565534786725),
 (626, 0.08696565534786725),
 (746, 0.08696565534786725),
 (787, 0.08696565534786725),
 (3028, 0.08696565534786725),
 (3140, 0.08696565534786725),
 (3235, 0.08696565534786725),
 (3310, 0.08696565534786725),
 (3423, 0.08696565534786725),
 (153, 0.086568731069961),
 (1898, 0.086568731069961),
 (1534, 0.08656873106996099),
 (51, 0.08586775814821836),
 (1639, 0.08586775814821836),
 (207, 0.0857142857142857),
 (634, 0.0857142857142857),
 (1161, 0.0857142857142857),
 (2253, 0.0857142857142857),
 (2644, 0.0857142857142857),
 (572, 0.08518354199999197),
 (1926, 0.08518354199999197),
 (3431, 0.08518354199999197),
 (37, 0.08451542547285165),
 (472, 0.08451542547285165),
 (534, 0.08451542547285165),
 (680, 0.08451542547285165),
 (776, 0.08451542547285165),
 (885, 0.08451542547285165),
 (987, 0.08451542547285165),
 (1401, 0.08451542547285165),
 (1614, 0.08451542547285165),
 (1621, 0.08451542547285165),
 (1655, 0.08451542547285165),
 (2165, 0.08451542547285165),
 (2203, 0.08451542547285165),
 (2712, 0.08451542547285165),
 (2801, 0.08451542547285165),
 (3389, 0.08451542547285165),
 (3527, 0.08451542547285165),
 (4061, 0.08451542547285165),
 (4431, 0.08451542547285165),
 (4641, 0.08451542547285165),
 (190, 0.08386278693775347),
 (82, 0.08336550215650926),
 (223, 0.08336550215650926),
 (254, 0.08336550215650926),
 (329, 0.08336550215650926),
 (471, 0.08336550215650926),
 (503, 0.08336550215650926),
 (632, 0.08336550215650926),
 (2683, 0.08336550215650926),
 (3355, 0.08336550215650926),
 (3470, 0.08336550215650926),
 (3910, 0.08336550215650926),
 (16, 0.08226127456606226),
 (71, 0.08226127456606226),
 (138, 0.08226127456606226),
 (1560, 0.08226127456606226),
 (1765, 0.08226127456606226),
 (2820, 0.08226127456606226),
 (4055, 0.08226127456606226),
 (4451, 0.08226127456606226),
 (62, 0.08199200616907877),
 (189, 0.08199200616907877),
 (205, 0.08199200616907877),
 (256, 0.08199200616907877),
 (850, 0.08199200616907877),
 (1045, 0.08199200616907877),
 (1323, 0.08199200616907877),
 (1664, 0.08199200616907877),
 (2326, 0.08199200616907877),
 (2763, 0.08199200616907877),
 (2789, 0.08199200616907877),
 (2882, 0.08199200616907877),
 (3155, 0.08199200616907877),
 (3253, 0.08199200616907877),
 (4473, 0.08199200616907877),
 (4568, 0.08199200616907877),
 (11, 0.081199794294115),
 (70, 0.081199794294115),
 (365, 0.081199794294115),
 (1289, 0.081199794294115),
 (1290, 0.081199794294115),
 (1367, 0.081199794294115),
 (2592, 0.081199794294115),
 (3206, 0.081199794294115),
 (3701, 0.081199794294115),
 (274, 0.08058229640253803),
 (59, 0.08024108542850393),
 (587, 0.08017837257372731),
 (737, 0.08017837257372731),
 (2163, 0.08017837257372731),
 (4640, 0.08017837257372731),
 (125, 0.07985957062499247),
 (109, 0.07968190728895957),
 (313, 0.07968190728895957),
 (800, 0.07968190728895957),
 (1288, 0.07968190728895957),
 (1521, 0.07968190728895957),
 (2161, 0.07968190728895957),
 (2317, 0.07968190728895957),
 (2381, 0.07968190728895957),
 (2410, 0.07968190728895957),
 (2551, 0.07968190728895957),
 (2659, 0.07968190728895957),
 (3398, 0.07968190728895957),
 (3430, 0.07968190728895957),
 (3832, 0.07968190728895957),
 (4412, 0.07968190728895957),
 (271, 0.0791945516022682),
 (732, 0.0791945516022682),
 (908, 0.0791945516022682),
 (2395, 0.0791945516022682),
 (2831, 0.0791945516022682),
 (3022, 0.0791945516022682),
 (3907, 0.0791945516022682),
 (229, 0.07913425882489307),
 (76, 0.07824607964359516),
 (79, 0.07824607964359516),
 (543, 0.07824607964359516),
 (591, 0.07824607964359516),
 (784, 0.07824607964359516),
 (979, 0.07824607964359516),
 (1175, 0.07824607964359516),
 (1325, 0.07824607964359516),
 (2021, 0.07824607964359516),
 (2052, 0.07824607964359516),
 (2363, 0.07824607964359516),
 (2701, 0.07824607964359516),
 (2916, 0.07824607964359516),
 (4083, 0.07824607964359516),
 (4123, 0.07824607964359516),
 (2354, 0.07824607964359515),
 (200, 0.07755667343294811),
 (1005, 0.07755667343294811),
 (1348, 0.07755667343294811),
 (1769, 0.07755667343294811),
 (2136, 0.07755667343294811),
 (2212, 0.07755667343294811),
 (3072, 0.07755667343294811),
 (3982, 0.07755667343294811),
 (4006, 0.07755667343294811),
 (9, 0.07733088933397005),
 (536, 0.07733088933397005),
 (674, 0.07733088933397005),
 (1623, 0.07733088933397005),
 (1632, 0.07733088933397005),
 (2241, 0.07733088933397005),
 (3188, 0.07733088933397005),
 (55, 0.07655590023509526),
 (212, 0.07644707871564382),
 (419, 0.07644707871564382),
 (782, 0.07644707871564382),
 (1446, 0.07644707871564382),
 (1883, 0.07644707871564382),
 (2650, 0.07644707871564382),
 (488, 0.07606982611289638),
 (179, 0.07559289460184544),
 (267, 0.07559289460184544),
 (570, 0.07559289460184544),
 (728, 0.07559289460184544),
 (827, 0.07559289460184544),
 (1146, 0.07559289460184544),
 (1168, 0.07559289460184544),
 (1292, 0.07559289460184544),
 (1770, 0.07559289460184544),
 (2533, 0.07559289460184544),
 (2698, 0.07559289460184544),
 (2787, 0.07559289460184544),
 (3390, 0.07559289460184544),
 (3822, 0.07559289460184544),
 (3994, 0.07559289460184544),
 (4099, 0.07559289460184544),
 (4403, 0.07559289460184544),
 (4443, 0.07559289460184544),
 (2056, 0.07476671794188403),
 (97, 0.07476671794188401),
 (262, 0.07476671794188401),
 (635, 0.07476671794188401),
 (665, 0.07476671794188401),
 (997, 0.07476671794188401),
 (1340, 0.07476671794188401),
 (1701, 0.07476671794188401),
 (1996, 0.07476671794188401),
 (183, 0.07466533929465573),
 (215, 0.07396705090823068),
 (704, 0.07396705090823068),
 (752, 0.07396705090823068),
 (1018, 0.07396705090823068),
 (2018, 0.07396705090823068),
 (2320, 0.07396705090823068),
 (4343, 0.07396705090823068),
 (100, 0.07377111135633174),
 (336, 0.07377111135633174),
 (1166, 0.07377111135633174),
 (1262, 0.07377111135633174),
 (1737, 0.07377111135633174),
 (1774, 0.07377111135633174),
 (1990, 0.07377111135633174),
 (2114, 0.07377111135633174),
 (3241, 0.07377111135633174),
 (3671, 0.07377111135633174),
 (3976, 0.07377111135633174),
 (4290, 0.07377111135633174),
 (30, 0.07319250547113999),

In [ ]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [ ]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [ ]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

In [ ]:
import pickle

In [ ]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
pip install streamlit

Requirement already satisfied: streamlit in /usr/local/lib/python3.7/dist-packages (1.5.1)
Requirement already satisfied: watchdog in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.1.6)
Requirement already satisfied: attrs in /usr/local/lib/python3.7/dist-packages (from streamlit) (21.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.19.5)
Requirement already satisfied: toml in /usr/local/lib/python3.7/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from streamlit) (21.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from streamlit) (6.0.1)
Requirement already satisfied: gitpython!=3.1.19 in /usr/local/lib/python3.7/dist-packages (from streamlit) (3.1.26)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (7.1.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from streamlit) (3.10.0.2)
Requirement already satisfied: altair>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (4.2.0)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.5.1)
Requirement already satisfied: validators in /usr/local/lib/python3.7/dist-packages (from streamlit) (0.18.2)
Requirement already satisfied: blinker in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (7.1.2)
Requirement already satisfied: pympler>=0.9 in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.23.0)
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (5.1.1)
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (4.2.4)
Requirement already satisfied: base58 in /usr/local/lib/python3.7/dist-packages (from streamlit) (2.1.1)
Requirement already satisfied: pandas>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (1.3.5)
Requirement already satisfied: protobuf!=3.11,>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from streamlit) (3.17.3)
Requirement already satisfied: astor in /usr/local/lib/python3.7/dist-packages (from streamlit) (0.8.1)
Requirement already satisfied: pydeck>=0.1.dev5 in /usr/local/lib/python3.7/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (0.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (4.3.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (0.11.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit) (2.11.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from gitpython!=3.1.19->streamlit) (4.0.9)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit) (5.0.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (5.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (0.18.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (4.10.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema>=3.0->altair>=3.2.0->streamlit) (3.7.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.21.0->streamlit) (2018.9)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.7/dist-packages (from protobuf!=3.11,>=3.6.0->streamlit) (1.15.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit) (7.6.5)
Requirement already satisfied: ipykernel>=5.1.2 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit) (6.9.0)
Requirement already satisfied: traitlets>=4.3.2 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit) (5.1.1)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (1.0.0)
Requirement already satisfied: jupyter-client<8.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (5.3.5)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (1.5.4)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (7.31.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.1.3)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (3.0.27)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (4.8.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (4.4.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.18.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (57.4.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (2.6.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.0.2)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.1.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (3.5.2)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.8.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->altair>=3.2.0->streamlit) (2.0.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (22.3.0)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (4.9.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.3.1)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.13.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.8.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.6.1)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.5.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.8.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (4.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->streamlit) (3.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->streamlit) (2.10)

In [ ]:
pip install pyngrok

Requirement already satisfied: pyngrok in /usr/local/lib/python3.7/dist-packages (5.1.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from pyngrok) (3.13)

In [ ]:
from pyngrok import ngrok

In [ ]:
%%writefile app.py
import pickle
import streamlit as st
import requests

def fetch_poster(movie_id):
    url = "https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US".format(movie_id)
    data = requests.get(url)
    data = data.json()
    poster_path = data['poster_path']
    full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    return full_path

def recommend(movie):
    index = movies[movies['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
    recommended_movie_names = []
    recommended_movie_posters = []
    for i in distances[1:6]:
        # fetch the movie poster
        movie_id = movies.iloc[i[0]].movie_id
        recommended_movie_posters.append(fetch_poster(movie_id))
        recommended_movie_names.append(movies.iloc[i[0]].title)

    return recommended_movie_names,recommended_movie_posters


st.header('Movie Recommender System')
movies = pickle.load(open('movie_list.pkl','rb'))
similarity = pickle.load(open('similarity.pkl','rb'))

movie_list = movies['title'].values
selected_movie = st.selectbox(
    "Type or select a movie from the dropdown",
    movie_list
)

if st.button('Show Recommendation'):
    recommended_movie_names,recommended_movie_posters = recommend(selected_movie)
    col1, col2, col3, col4, col5 = st.columns(5)
    with col1:
        st.text(recommended_movie_names[0])
        st.image(recommended_movie_posters[0])
    with col2:
        st.text(recommended_movie_names[1])
        st.image(recommended_movie_posters[1])

    with col3:
        st.text(recommended_movie_names[2])
        st.image(recommended_movie_posters[2])
    with col4:
        st.text(recommended_movie_names[3])
        st.image(recommended_movie_posters[3])
    with col5:
        st.text(recommended_movie_names[4])
        st.image(recommended_movie_posters[4])

Overwriting app.py

In [ ]:
!streamlit run app.py & npx localtunnel --port 8501

2022-02-10 05:59:22.852 INFO    numexpr.utils: NumExpr defaulting to 2 threads.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:8501
  External URL: http://34.83.30.151:8501

npx: installed 22 in 15.578s
your url is: https://ugly-elephant-19.loca.lt
  Stopping...
^C